// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDNcoS-aXC8AFmBG92qF_SDLxFEoK3Mg',
    appId: '1:204689348332:web:f3744fc8f824e32bac37c9',
    messagingSenderId: '204689348332',
    projectId: 'mongrh-b54b0',
    authDomain: 'mongrh-b54b0.firebaseapp.com',
    storageBucket: 'mongrh-b54b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs0psAMwuZj78-1Ia70ax-2FR15dHfjRE',
    appId: '1:204689348332:android:71348523947b2619ac37c9',
    messagingSenderId: '204689348332',
    projectId: 'mongrh-b54b0',
    storageBucket: 'mongrh-b54b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQMRF33_aqIWJBpBIIff2VojvwF4YFRY',
    appId: '1:204689348332:ios:89cdf9433abd8c57ac37c9',
    messagingSenderId: '204689348332',
    projectId: 'mongrh-b54b0',
    storageBucket: 'mongrh-b54b0.appspot.com',
    iosBundleId: 'com.example.mongrh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQMRF33_aqIWJBpBIIff2VojvwF4YFRY',
    appId: '1:204689348332:ios:5121b2f102daf5a5ac37c9',
    messagingSenderId: '204689348332',
    projectId: 'mongrh-b54b0',
    storageBucket: 'mongrh-b54b0.appspot.com',
    iosBundleId: 'com.example.mongrh.RunnerTests',
  );
}
